{
 "title": "Lilly-SAT",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job:",
    "query": {
     "query": "label_values(visor_chain_node_height,job)"
    }
   },
   { "name": "PostgresqlDB", "label": "DB:", "query": "postgres" }
  ]
 },
 "panels": [
  { "title": "Realtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "visor_peer_count{job=\"$job\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "((visor_job_start_total{job=\"$job\"} unless visor_job_complete_total{job=\"$job\"}) unless visor_job_error_total{job=\"$job\"}) unless visor_job_timeout{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Heights",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "visor_chain_node_height_expected{job=\"$job\"}"
    },
    {
     "expr": "visor_chain_node_height{job=\"$job\"}"
    },
    {
     "expr": "visor_chain_node_worker_height{job=\"$job\"}"
    },
    {
     "expr": "# DIsplay only if a watch is running\nvisor_watch_height{job=\"$job\"}"
    },
    {
     "expr": "# Filter running Jobs only\nlabel_replace(visor_tipset_height{job=\"$job\"} * on (exported_job) (((visor_job_start_total{job=\"$job\"} unless visor_job_complete_total{job=\"$job\"}) unless visor_job_error_total{job=\"$job\"}) unless visor_job_timeout{job=\"$job\"}), \"__name__\", \"Running Job\", \"\",\"\")"
    }
   ]
  },
  {
   "title": "Skipped tipsets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "increase(visor_tipset_skip_total[2m])",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Highest TipSet by Actor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(visor_tipset_height{job=\"$job\"}) by (task)",
     "legendFormat": "{{exported_job}} - {{task}}"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(((visor_job_start_total{job=\"$job\", exported_job=~\"find_.*\"} unless visor_job_complete_total{job=\"$job\", exported_job=~\"find_.*\"}) unless visor_job_error_total{job=\"$job\", exported_job=~\"find_.*\"}) unless visor_job_timeout{job=\"$job\", exported_job=~\"find_.*\"})"
    },
    {
     "expr": "count(((visor_job_start_total{job=\"$job\", exported_job=~\"gap_.*\"} unless visor_job_complete_total{job=\"$job\", exported_job=~\"gap_.*\"}) unless visor_job_error_total{job=\"$job\", exported_job=~\"gap_.*\"}) unless visor_job_timeout{job=\"$job\", exported_job=~\"gap_.*\"})"
    },
    {
     "expr": "count(((visor_job_start_total{job=\"$job\", exported_job=~\"watch_.*\"} unless visor_job_complete_total{job=\"$job\", exported_job=~\"watch_.*\"}) unless visor_job_error_total{job=\"$job\", exported_job=~\"watch_.*\"}) unless visor_job_timeout{job=\"$job\", exported_job=~\"watch_.*\"})"
    },
    {
     "expr": "count(((visor_job_start_total{job=\"$job\", exported_job=~\"walk_.*\"} unless visor_job_complete_total{job=\"$job\", exported_job=~\"walk_.*\"}) unless visor_job_error_total{job=\"$job\", exported_job=~\"walk_.*\"}) unless visor_job_timeout{job=\"$job\", exported_job=~\"walk_.*\"})"
    },
    {
     "expr": "count(((visor_job_start_total{job=\"$job\", exported_job!~\"find_.*|gap_.*|watch_.*|walk_.*\"} unless visor_job_complete_total{job=\"$job\", exported_job!~\"find_.*|gap_.*|watch_.*|walk_.*\"}) unless visor_job_error_total{job=\"$job\", exported_job!~\"find_.*|gap_.*|watch_.*|walk_.*\"}) unless visor_job_timeout{job=\"$job\", exported_job!~\"find_.*|gap_.*|watch_.*|walk_.*\"})"
    }
   ]
  },
  {
   "title": "Average Processing Duration [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(visor_processing_duration_ms_sum[5m]) / rate(visor_processing_duration_ms_count[5m])\n",
     "legendFormat": "{{api}} {{task}}"
    }
   ]
  },
  {
   "title": "Processed TipSet by Job/Actor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "# Filter running Jobs only\nlabel_replace(visor_tipset_height{job=\"$job\"} * on (exported_job) group_left() (((visor_job_start_total{job=\"$job\"} unless visor_job_complete_total{job=\"$job\"}) unless visor_job_error_total{job=\"$job\"}) unless visor_job_timeout{job=\"$job\"}), \"__name__\", \"Running Job\", \"\",\"\")",
     "legendFormat": "{{exported_job}} - {{task}}"
    }
   ]
  },
  {
   "title": "Average Persist Duration [5m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(visor_persist_duration_ms_sum[5m]) / rate(visor_persist_duration_ms_count[5m])",
     "legendFormat": "{{api}} {{task}}"
    }
   ]
  },
  { "title": "Tipsets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Tipsets - COMPLETED",
   "type": "heatmap",
   "description": "Tipsets successfully processed and completed",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "-- Bug in Grafana  handling paranthesis in the $__unixEpochGroupAlias macro => usage of *1000/$__interval_ms #Commit https://github.com/grafana/grafana/pull/46764\nSELECT\n  $__unixEpochGroupAlias(height*30*1000/$__interval_ms+1598306400,$__interval),\n  (EXTRACT (MINUTE FROM to_timestamp(visor_processing_reports.height*30+1598306400)) + EXTRACT (SECOND FROM to_timestamp(visor_processing_reports.height*30+1598306400))/60) AS minutes\nFROM visor_processing_reports\nWHERE\n  $__unixEpochFilter(height*30+1598306400) and (status = 'OK' or status_information = 'NULL_ROUND')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Tipsets - OBSERVED",
   "type": "heatmap",
   "description": "All tipsets that have been observed by a job. Tipset can be completed/skipped or in error ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "rawSql": "-- Bug in Grafana  handling paranthesis in the $__unixEpochGroupAlias macro => usage of *1000/$__interval_ms #Commit https://github.com/grafana/grafana/pull/46764\nSELECT\n  $__unixEpochGroupAlias(height*30*1000/$__interval_ms+1598306400,$__interval),\n  (EXTRACT (MINUTE FROM to_timestamp(visor_processing_reports.height*30+1598306400)) + EXTRACT (SECOND FROM to_timestamp(visor_processing_reports.height*30+1598306400))/60) AS minutes\nFROM visor_processing_reports\nWHERE\n  $__unixEpochFilter(height*30+1598306400)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Tipsets - GAP report",
   "type": "heatmap",
   "description": "All gap reported by gap report",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "rawSql": "-- Bug in Grafana  handling paranthesis in the $__unixEpochGroupAlias macro => usage of *1000/$__interval_ms #Commit https://github.com/grafana/grafana/pull/46764\nSELECT\n  $__unixEpochGroupAlias(height*30*1000/$__interval_ms+1598306400,$__interval),\n  (EXTRACT (MINUTE FROM to_timestamp(visor_gap_reports.height*30+1598306400)) + EXTRACT (SECOND FROM to_timestamp(visor_gap_reports.height*30+1598306400))/60) AS minutes\n\nFROM visor_gap_reports\nWHERE\n  $__unixEpochFilter(height*30+1598306400)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Tipsets - SKIPPED",
   "type": "heatmap",
   "description": "All tipsets that have been skipped",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "-- Bug in Grafana  handling paranthesis in the $__unixEpochGroupAlias macro => usage of *1000/$__interval_ms #Commit https://github.com/grafana/grafana/pull/46764\nSELECT\n  $__unixEpochGroupAlias(height*30*1000/$__interval_ms+1598306400,$__interval),\n  (EXTRACT (MINUTE FROM to_timestamp(visor_processing_reports.height*30+1598306400)) + EXTRACT (SECOND FROM to_timestamp(visor_processing_reports.height*30+1598306400))/60) AS minutes\nFROM visor_processing_reports\nWHERE\n  $__unixEpochFilter(height*30+1598306400) and (status = 'SKIP')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Tipsets - ERRORS",
   "type": "heatmap",
   "description": "All tipsets in error",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "rawSql": "-- Bug in Grafana  handling paranthesis in the $__unixEpochGroupAlias macro => usage of *1000/$__interval_ms #Commit https://github.com/grafana/grafana/pull/46764\nSELECT\n  $__unixEpochGroupAlias(height*30*1000/$__interval_ms+1598306400,$__interval),\n  (EXTRACT (MINUTE FROM to_timestamp(visor_processing_reports.height*30+1598306400)) + EXTRACT (SECOND FROM to_timestamp(visor_processing_reports.height*30+1598306400))/60) AS minutes\nFROM visor_processing_reports\nWHERE\n  $__unixEpochFilter(height*30+1598306400) and (status = 'ERROR')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Historical graph of Realtime indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "visor_peer_count{job=\"$job\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "Height diff",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "visor_chain_node_height_expected{job=\"$job\"} - visor_chain_node_height{job=\"$job\"}",
     "legendFormat": "Node"
    },
    {
     "expr": "visor_chain_node_height_expected{job=\"$job\"} - visor_chain_node_worker_height{job=\"$job\"}",
     "legendFormat": "Worker"
    }
   ]
  },
  {
   "title": "Running jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((visor_job_start_total{job=\"$job\"} unless visor_job_complete_total{job=\"$job\"}) unless visor_job_error_total{job=\"$job\"}) unless visor_job_timeout{job=\"$job\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  }
 ]
}